### ISSUE TITLE
team names mismatch and missing countries

### ISSUE THREAD

**Issue by lorenzocarli83** [tonyelhabr/club-rankings#1]
Hi, I have looked at the rankings comparison csv and have a few comments:
1) there is a mismatch in some of the teams names among the different ranking systems. 
2) Vaduz is not a swiss team according to Clubelo , this could explain why there is such a big difference among the ratings for this team
3) FiveThirtyEight includes about 32 leagues worldwide, Clubelo covers about the same amount but only for European leagues, while Opta covers many more. it would be interesting to extend the comparison to all teams , taking Opta as reference. For example: lot of teams playing in UECL, UEL and UCL are not covered by FiveThirtyEight, but they are covered by Clubelo and Opta

**Comment by tonyelhabr** [comment]
Hey, thanks for expressing interest in this project. You're welcome to make a PR to address your concerns, and I will merge it upon review.

For (3), I agree that it would be interesting to be able to compare Opta and clubelo rankings for teams that aren't in 538's rankings. I wanted to eventually do that, but haven't had the time.

**Comment by tonyelhabr** [comment]
1. Addressed one known mismatch.
2. Did nothing here.
3. Removed 538. Started to use Opta as the "base" for comparison.
